<?php

namespace web\tmp\common\header;

/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 18-6-2016
 * Time: 21:33
 */

$data    = unserialize( CMS_GET_DATA );
$allowed = ['requestAttribute'];

if( !empty( $data ) ):
    foreach( $data as $key => $value ):
        if( in_array( $key, $allowed ) ) ${$key} = $value;
    endforeach;
endif;

$requestAttribute = ( !empty( $requestAttribute ) ? $requestAttribute : "" );

$urlDataHome     = base64_encode( json_encode( array( "requestType" => "template", "requestAttribute" => "home", "requestDirectory" => "common" ) ) );
$urlDataProjects = base64_encode( json_encode( array( "requestType" => "template", "requestAttribute" => "projects", "requestDirectory" => "project" ) ) );

?>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="keywords" content="">
        <meta name="robots" content="nofollow">
        <meta property="og:title" content="Control Management System">
        <meta property="og:type" content="website">
        <meta property="og:description" content="">
        <meta property="og:url" content="">
        <meta property="og:image" content="">
        <link href='https://fonts.googleapis.com/css?family=Raleway%7cPassion+One%7cWork+Sans%7cRoboto+Condensed:400' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="css/style.css">

        <script src="https://code.jquery.com/jquery-2.2.3.min.js"
                integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="
                crossorigin="anonymous"></script>
        <script type="text/javascript" src="js/functions.js"></script>
        <title>QuaRatio</title>
    </head>
        <body>
            <header>
                <div class="header">
                    <div class="header-Logo">QuaRatio <span>- Content Management System</span></div>
                </div>
            </header>
            <?php if( !empty( $_SESSION['userId'] ) ): ?>
            <nav>
                <div class="menuItem <?= ( $requestAttribute === "home" ? "menuSelected" : ( empty( $requestAttribute ) ? "menuSelected" : "" ) ) ?>">
                    <a href="<?= LITENING_SELF.'?data='.$urlDataHome; ?>">Home</a>
                </div>
                <div class="menuItem
                    <?= ( $requestAttribute === "projects"
                          || $requestAttribute === "newProject"
                          || $requestAttribute === "xmlModelUpload"
                          || $requestAttribute === "projectManager"
                          ? "menuSelected" : "" ) ?>">
                    <a href="<?= LITENING_SELF.'?data='.$urlDataProjects; ?>">Projects</a>
                </div>
                <div class="menuItem">
                    <a href="">Database</a>
                </div>
                <div class="menuItem">
                    <a href="">Account</a>
                </div>
            </nav>
            <?php endif; ?>
            <script>

                $('a').click(function (event){
                    var href = this.href;
                    event.preventDefault();
                    $.ajax({
                        url: $(this).attr('href'),
                        dataType :'json',
                        data : '{}',
                        success:  document.location = href;
                })
                    return false;
                });
            </script>