<?php

/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 17-6-2016
 * Time: 17:49
 */

namespace web\tmp\common\home;

use \application\controller;
use application\classes\iOXMLModelParser;

( new controller\Controller( "class", "iOXMLModelParser", "iOXMLModelParser" ) )->request();

$xmlFile = $_SERVER['DOCUMENT_ROOT'] . '/quaratio/web/files/test2.xml';

$parsedXML = ( new iOXMLModelParser\IOXMLModelParser( $xmlFile ) )->parseXMLModel();

echo '<pre>';
print_r($parsedXML);

?>

