<?php

namespace web\tmp\register;

use application\controller;

/*
* Request the register handler when the REQUEST_METHOD is POST
* Create variables of get data when the REQUEST_METHOD is GET
* Only create variables of allowed data (data allowed on this specific page)
*/

if($_SERVER['REQUEST_METHOD'] === "POST"):

    (new controller\Controller( "handler", "register", "register" ))->request();

elseif($_SERVER['REQUEST_METHOD'] === "GET"):

    $data    = unserialize(CMS_GET_DATA);
    $allowed = ['error', 'email', 'emailError', 'passwordError', 'passwordRepeatError'];

    if(!empty($data)):

        foreach($data as $key => $value):

            if(in_array($key, $allowed)) ${$key} = $value;

        endforeach;

    endif;

endif;

$error                = (!empty($error) ? $error : "");
$email                = (!empty($email) ? $email : "");
$emailError           = (!empty($emailError) ? $emailError : "");
$passwordError        = (!empty($passwordError) ? $passwordError : "");
$passwordRepeatError  = (!empty($passwordRepeatError) ? $passwordRepeatError : "");

// Url data array's

$urlDataLogin = array();
$urlDataLogin['requestType']      = "template";
$urlDataLogin['requestAttribute'] = "login";
$urlDataLogin['requestDirectory'] = "login";
$urlDataLogin                     = base64_encode( json_encode( $urlDataLogin ) );

$urlDataRegister = array();
$urlDataRegister['requestType']      = "template";
$urlDataRegister['requestAttribute'] = "register";
$urlDataRegister['requestDirectory'] = "register";
$urlDataRegister                     = base64_encode( json_encode( $urlDataRegister ) );

?>

<div class="login">
    <div class="loginTitle">Sign-up <span><a href="<?php echo LITENING_SELF; ?>?data=<?php echo $urlDataLogin; ?>">back to login</a></span></div>
    <div class="loginMessage">
        <?php

            if(!empty($error)):

                echo'<div class="loginMessage-Msg redText">';

                switch($error):
                    case"noEmail":
                        echo'Please fill in your email adress.';
                        break;
                    case"emailExists":
                        echo'The email adress you entered already exists.';
                        break;
                    case"invalidEmail":
                        echo'The email adress you entered is not valid. ';
                        break;
                    case"noPassword":
                        echo'Please fill in your password.';
                        break;
                    case"passwordTooLong":
                        echo'The password you entered is too long. (Max 16 characters)';
                        break;
                    case"noPasswordRepeat":
                        echo'Repeat your password, please.';
                        break;
                    case"noMatch":
                        echo'The passwords you entered did not match.';
                        break;
                    default:
                        break;
                endswitch;

                echo'</div>';

            else:

                echo'<div class="loginMessage-Msg">';
                echo'Please fill in your email and password.';
                echo'</div>';

            endif;

        ?>
        <form action="<?php echo LITENING_SELF; ?>?data=<?php echo $urlDataRegister; ?>" method="POST">
            <div class="loginBox">
                <div class="loginLeft
                    <?php
                    if($emailError === "empty" ||
                        $error === 'emailExists' ||
                        $emailError === "notValid"):
                            echo 'redText';
                    endif;
                    ?>
                    "><span id="email">Email</span>
                </div>
                <div class="loginRight">
                    <input type="email" name="email" placeholder="Your e-mail adress"
                        <?php
                        if(!empty($email)): echo 'value="'.$email.'"'; endif;
                        if($emailError === "empty"):
                            echo 'class="redBorder"';
                            echo 'autofocus';
                        elseif($emailError === "notValid"):
                            echo 'class="redBorder"';
                        elseif(empty($error)):
                           echo'autofocus';
                        elseif($error === 'emailExists'):
                            echo 'class="redBorder"';
                        endif;
                        ?>
                    >
                </div>
            </div>
            <div class="loginBox">
                <div class="loginLeft
                    <?php
                    if($passwordError === "empty" ||
                        $error === "passwordTooLong"):
                        echo 'redText';
                    endif;
                    ?>
                "><span id="password">Password</span>
                </div>
                <div class="loginRight">
                    <input type="password" name="password" placeholder="Fill in a password"
                       <?php
                        if($passwordError === "empty" ||
                            $error === "passwordTooLong"):
                           echo 'class="redBorder"';
                        endif;
                       ?>
                   >
                </div>
            </div>
            <div class="loginBox">
                <div class="loginLeft
                    <?php
                    if($passwordRepeatError === "empty" || $error === 'noMatch'):  echo 'loginRedText'; endif;
                    ?>
                "><span id="passwordRepeat">Repeat password</span>
                </div>
                <div class="loginRight">
                    <input type="password" name="passwordRepeat" placeholder="Repeat the password, please"
                       <?php
                        if($passwordRepeatError === "empty" || $error === 'noMatch'):
                           echo 'class="redBorder"';
                        endif;
                       ?>
                    >
                </div>
            </div>
            <div class="loginBox">
                <div class="loginSubmit"><input type="submit" name="submit" value="Sign up"></div>
            </div>
        </form>
    </div>
</div>

<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $(function() {
        $('input').on('focus blur', function () {
            var name = $(this).attr('name');
            switch(name)
                {
                    case"email":
                        $('#email').css('color', '#000000');
                        break;
                    case"password":
                    $('#password').css('color', '#000000');
                        break;
                    case"passwordRepeat":
                    $('#passwordRepeat').css('color', '#000000');
                        break;
                    default:
                        break;
                }
        });
    });
});
</script>