<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 28-7-2016
 * Time: 21:09
 */

namespace web\tmp\project\projectManager;

use \application\controller;
use application\classes\project;
use application\classes\iOXMLEAModel;

( new controller\Controller( "class", "project", "project" ) )->request();
( new controller\Controller( "class", "iOXMLEAModel", "iOXMLEAModel" ) )->request();

$projects = ( new project\Project( "getAllProjectsByUser" ) )->request( $params = null );

$urlDataPreview = array( "requestType" => "template", "requestAttribute" => "preview", "requestDirectory" => "xmlModel" );
$urlDataProjectDelete = array( "requestType" => "ajax", "requestAttribute" => "deleteProject", "requestDirectory" => "project" );

?>

<div class="project effect3">
    <div class="project-Title">Project Manager</div>
    <div class="project-Header">
        <p>
            Projects can be managed within the project manager and exchanged with other QuaRatio members.
           <br><br>
            With the project manager you can:
            <br>
            <ul>
                <li>Browse your projects</li>
                <li>Edit projects</li>
                <li>Share projects</li>
            </ul>
        </p>
    </div>
</div>


<div class="projects">

    <div class="projects-item projects-head">
        <div class="projects-item-name">Project</div>
        <div class="projects-item-descr">Description</div>
        <div class="projects-item-date">Date</div>
        <div class="projects-item-model">Model</div>
        <div class="projects-item-calculator">Calc</div>
        <div class="projects-item-active">Active</div>
    </div>


    <div id="main">
    <div class="inner">
    <?php foreach( $projects as $project ): ?>
        <?php

            $params    = array( "project_id" => $project['id'] );
            $urlDataProjectDelete['projectId'] = $project['id'];

            $modelData = ( new project\Project( "getModelIdByProjectId" ) )->request( $params );

            if( !empty( $modelData ) ):

                $hasModel = true;
                $modelId = $modelData['model_id'];

                $urlDataPreview['xmlModelId'] = $modelId;

                $model = ( new iOXMLEAModel\IOXMLEAModel( $modelId ) )->getModel();

            else:

                $hasModel = false;

            endif;

        ?>

        <div class="projects-item">
            <div class="projects-item-name"><?= $project['name']; ?></div>
            <div class="projects-item-descr"><?= $project['description']; ?></div>
            <div class="projects-item-date"><?= $project['date'].$project['time']; ?></div>
            <div class="projects-item-model"><?= ( $hasModel === true ? "yes" : "no" ); ?></div>
            <div class="projects-item-calculator">no</div>
            <div class="projects-item-active">no</div>

            <div class="projects-item-control">
                <div id="ajaxResponse" class="project-form-message"></div>
                <div class="projects-item-modelLink"><a href="<?= LITENING_SELF.'?data='. base64_encode( json_encode( $urlDataPreview ) ) ?>">model</a></div>
                <div class="projects-item-modelLink"><a href="">calculator</a></div>
                <div class="projects-item-modelLink"><a href="">Edit</a></div>
                <div class="projects-item-modelLink">
                    <form class="deleteProject" action="" method="POST">
                        <input type="hidden" class="projectId" name="projectId" value="<?= $project['id']; ?>">
                        <button name="submit" type="submit" class="submit">Delete</button>
                    </form>
                </div>
            </div>
        </div>



        <?php endforeach; ?>
        </div>
        </div>

    <script>
        $(".submit").click(function(e) {
            var $project = $(this).closest('.projects-item');

            var url = "../application/ajax/project/deleteProject.php";
            var parentObj = $(this).closest('.deleteProject');
            var id = parentObj.find('.projectId').val();

            $.ajax({
                type: "POST",
                url: url,
                data: { projectId: id },
                dataType: "json",
                success: function(response)
                {

                    if(response.delete) $project.remove();
                }
            });

            e.preventDefault();
        });
    </script>

</div>
