<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 28-7-2016
 * Time: 21:09
 */

namespace web\tmp\project\projectManager;

use \application\controller;
use application\classes\project;
use application\classes\iOXMLEAModel;

( new controller\Controller( "class", "project", "project" ) )->request();
( new controller\Controller( "class", "iOXMLEAModel", "iOXMLEAModel" ) )->request();

$projects = ( new project\Project( "getAllProjectsByUser" ) )->request( $params = null );

?>

<div class="project effect3">
    <div class="project-Title">Project Manager</div>
    <div class="project-Header">
        <p>
            Projects can be managed within the project manager and exchanged with other QuaRatio members.
           <br><br>
            With the project manager you can:
            <br>
            <ul>
                <li>Browse your projects</li>
                <li>Edit projects</li>
                <li>Share projects</li>
            </ul>
        </p>
    </div>
</div>

<div class="projects">

    <div class="projects-item projects-head">
        <div class="projects-item-name">Project</div>
        <div class="projects-item-descr">Description</div>
        <div class="projects-item-date">Date</div>
        <div class="projects-item-model">Model</div>
        <div class="projects-item-calculator">Calc</div>
        <div class="projects-item-active">Active</div>
    </div>

    <?php foreach( $projects as $project ): ?>
        <?php

            $params  = array( "project_id" => $project['id'] );
            $modelId = ( new project\Project( "getModelIdByProjectId" ) )->request( $params );
            $modelId = ( new iOXMLEAModel\IOXMLEAModel( $modelId ) )->getModel();

        ?>
        <div class="projects-item">
            <div class="projects-item-name"><?= $project['name']; ?></div>
            <div class="projects-item-descr"><?= $project['description']; ?></div>
            <div class="projects-item-date"><?= $project['date'].$project['time']; ?></div>
            <div class="projects-item-model">hh</div>
            <div class="projects-item-calculator">no</div>
            <div class="projects-item-active">no</div>
        </div>
        <div class="projects-item-control">
            <div class="projects-item-modelLink"><a href="">model</a></div>
            <div class="projects-item-modelLink"><a href="">calculator</a></div>
            <div class="projects-item-modelLink"><a href="">Edit</a></div>
        </div>
    <?php endforeach; ?>

</div>
