<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 25-Jul-16
 * Time: 13:11
 */

namespace web\tmp\xmlModel\preview;

use \application\controller;
use \application\classes\iOXMLEAScreenFactory;

( new controller\Controller( "class", "iOXMLEAScreenFactory", "iOXMLEAScreenFactory" ) )->request();

$data    = unserialize( CMS_GET_DATA );
$allowed = ['xmlModelId'];

if( !empty( $data ) ):
    foreach( $data as $key => $value ):
        if( in_array( $key, $allowed ) ) ${$key} = $value;
    endforeach;
endif;

$xmlModel = ( isset( $xmlModelId ) ? $xmlModelId : "" );

$orderedElements = ( new iOXMLEAScreenFactory\IOXMLEAScreenFactory( $xmlModel ) )->extractAndOrderElements();
$totalElements   = count( $orderedElements );

//var_dump($orderedElements);

for( $i = 0; $i < $totalElements; $i++ ):

    if( $orderedElements[$i]['root'] === 'true' ):
        $element = ( new iOXMLEAScreenFactory\IOXMLEAScreenFactory( $orderedElements[$i] ) )->createIntro();
        print_r($element);

    else:

        $element = ( new iOXMLEAScreenFactory\IOXMLEAScreenFactory( $orderedElements[$i] ) )->createElement();

        print_r($element);

        echo '<pre>';
        print_r($orderedElements[$i]);

    endif;

endfor;

//var_dump($orderedElements);

