<?php
/**
 * Created by PhpStorm.
 * User: Ruben Hazenbosch
 * Date: 25-Jul-16
 * Time: 13:11
 */

namespace web\tmp\xmlModel\preview;

use \application\controller;
use \application\classes\iOXMLEAScreenFactory;

( new controller\Controller( "class", "iOXMLEAScreenFactory", "iOXMLEAScreenFactory" ) )->request();

$data    = unserialize( CMS_GET_DATA );
$allowed = ['xmlModelId'];

if( !empty( $data ) ):
    foreach( $data as $key => $value ):
        if( in_array( $key, $allowed ) ) ${$key} = $value;
    endforeach;
endif;

$xmlModel = ( isset( $xmlModelId ) ? $xmlModelId : "" );

$orderedElements = ( new iOXMLEAScreenFactory\IOXMLEAScreenFactory( $xmlModel ) )->extractAndOrderElements();
$totalElements   = count( $orderedElements );

for( $i = 0; $i < $totalElements; $i++ ):

    $form = ( new iOXMLEAScreenFactory\IOXMLEAScreenFactory( $orderedElements[$i] ) )->createForm();

endfor;

