<?php

namespace web\tmp\xmlModel\xmlModelReport;

$data    = unserialize( CMS_GET_DATA );
$allowed = ['hideValidatorType'];

if( !empty( $data ) ):
    foreach( $data as $key => $value ):
        if( in_array( $key, $allowed ) ) ${$key} = $value;
    endforeach;
endif;

$hideValidatorType = ( !empty( $hideValidatorType ) ? $hideValidatorType : "" );

/**
 * Get the report session and unserialize it
 */
$report = unserialize( $_SESSION['xmlValidatorReport'] );

if( isset( $report['file_exists'] ) && $report['file_exists'] === true ):
    $fileExists = true;
    $validationMessage = "Validation failed";
endif;

$requestTypeHide      = "template";
$requestAttributeHide = "xmlModelReport";
$requestDirectoryHide = "xmlModel";
$hideValidatorWarning = "warning";
$urlDataHide = array( "requestType" => $requestTypeHide, "requestAttribute" => $requestAttributeHide, "requestDirectory" => $requestDirectoryHide, "hideValidatorType" => $hideValidatorWarning );
$urlDataHide = base64_encode( json_encode( $urlDataHide ) );

$requestTypeShow      = "template";
$requestAttributeShow = "xmlModelReport";
$requestDirectoryShow = "xmlModel";
$urlDataShow = array( "requestType" => $requestTypeShow, "requestAttribute" => $requestAttributeShow, "requestDirectory" => $requestDirectoryShow );
$urlDataShow = base64_encode( json_encode( $urlDataShow ) );

$requestTypeUpload      = "template";
$requestAttributeUpload = "home";
$requestDirectoryUpload = "common";
$urlDataUpload = array( "requestType" => $requestTypeUpload, "requestAttribute" => $requestAttributeUpload, "requestDirectory" => $requestDirectoryUpload );
$urlDataUpload = base64_encode( json_encode( $urlDataUpload ) );

//var_dump($report);

?>

<div class="modelReport">

    <div class="modelReport-Title">XML Report - Enterprise Architect Model</div>

        <div class="modelReport-container">
                <div class="modelReport-totalValidation <?= ( $report['validation']['valid'] === true && isset( $fileExists) !== true ? "totalValidationGreen" : "totalValidationRed" ) ?>">
                    <?= ( isset( $fileExists ) && $fileExists === true ? $validationMessage : $report['validation']['message'] ); ?>
                </div>
                <div class="modelReport-totalErrorTypes">
                    <div class="modelReport-totalErrorType">Severe ( <?= $report['totalErrorTypes']['severe']; ?> )</div>
                    <div class="modelReport-totalErrorType">Errors ( <?= $report['totalErrorTypes']['error']; ?> )</div>
                    <div class="modelReport-totalErrorType">
                        Warnings ( <?= $report['totalErrorTypes']['warning']; ?> )
                        <?php if( $hideValidatorType === "warning" ): ?>
                            <a href="<?= LITENING_SELF."?data=".$urlDataShow; ?>">show</a>
                        <?php else: ?>
                            <a href="<?= LITENING_SELF."?data=".$urlDataHide; ?>">hide</a>
                        <?php endif; ?>
                    </div>
                    <div class="modelReport-totalErrorType">Info ( <?= $report['totalErrorTypes']['info']; ?> )</div>
                    <div class="modelReport-totalErrorType">Valid ( <?= $report['totalErrorTypes']['valid']; ?> )</div>
                </div>

                <div class="modelReport-totalErrorTypes">
                    <div class="modelReport-totalErrorType"><a href="<?= LITENING_SELF.'?data='.$urlDataUpload; ?>">terug naar uploaden</a></div>
                </div>

            <?php
            if( !empty( $report['file_exists'] ) && $report['file_exists'] === true ):
                echo '<div class="modelReport-exists">';
                echo 'Het model bestaat al!';
                echo '</div>';
            else:
            ?>

            <div class="modelReport-item modelReport-grayBack">
                <div class="modelReport-item-img">
                    <img src="./images/icons/list_icon.png">
                    <div class="modelReport-item-type"><small> - type</small></div>
                </div>
                <div class="modelReport-item-name">Subject</div>
                <div class="modelReport-item-value">Information</div>
                <div class="modelReport-item-message">Description</div>
            </div>

            <?php

                foreach( $report as $key => $v ):

                    if( !empty( $report[$key]['type'] ) && $key !== "validation" ):

                        if( $report[$key]['type'] !== $hideValidatorType ):

                            ?>

                            <div class="modelReport-item">
                                <?php $type = $report[$key]['type']; ?>
                                <div class="modelReport-item-img">
                                    <img src="./images/icons/<?= ( $type === "warning" || $type === "info" ? "warning_icon.png" : ( $type === "severe" || $type === "error" ? "red_cross_icon.png" : "checkgreen_icon.png") ); ?>">
                                    <div class="modelReport-item-type"> - <?= $report[$key]['type']; ?></div>
                                </div>
                                <div class="modelReport-item-name"><?= $report[$key]['name']; ?></div>
                                <div class="modelReport-item-value"><?= $report[$key]['value']; ?></div>
                                <div class="modelReport-item-message"><?= $report[$key]['message']; ?></div>

                                <?php if( $report[$key]['valid'] === false ): ?>
                                        <div class="modelReport-item-info">
                                            <img src="./images/icons/arrow_right_up.png"><span><?= $report[$key]['info']; ?></span>
                                        </div>
                                <?php endif; ?>

                            </div> <?php

                        endif;

                    endif;

                endforeach;

                /**
                 *
                 */
                if( !empty( $report['initialValueType'] ) ):

                    foreach( $report['initialValueType'] as $initialValueType => $value ):

                        $totalInitialValueTypes = count( $report['initialValueType'][$initialValueType] );

                        for( $i = 0; $i < $totalInitialValueTypes; $i++ ):

                            if( isset( $report['initialValueType'][$initialValueType]['type'.($i+1)] ) ):

                                if( $report['initialValueType'][$initialValueType]['type'.($i+1)]['type'] !== $hideValidatorType ):

                                    ?>

                                    <div class="modelReport-item">
                                        <?php $type = $report['initialValueType'][$initialValueType]['type'.($i+1)]['type']; ?>
                                        <div class="modelReport-item-img">
                                            <img src="./images/icons/<?= ( $type === "warning" || $type === "info" ? "warning_icon.png" : ( $type === "severe" || $type === "error" ? "red_cross_icon.png" : "checkgreen_icon.png") ); ?>">
                                            <div class="modelReport-item-type"> - <?= $report['initialValueType'][$initialValueType]['type'.($i+1)]['type']; ?></div>
                                        </div>
                                        <div class="modelReport-item-name"><?= $report['initialValueType'][$initialValueType]['type'.($i+1)]['name']; ?></div>
                                        <div class="modelReport-item-value"><?= $report['initialValueType'][$initialValueType]['type'.($i+1)]['value']; ?></div>
                                        <div class="modelReport-item-message"><?= $report['initialValueType'][$initialValueType]['type'.($i+1)]['message']; ?></div>

                                        <?php if( $report['initialValueType'][$initialValueType]['type'.($i+1)]['valid'] === false ): ?>
                                            <div class="modelReport-item-info">
                                                <img src="./images/icons/arrow_right_up.png"><span><?= $report['initialValueType'][$initialValueType]['type'.($i+1)]['info']; ?></span>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <?php

                                endif;

                            endif;

                        endfor;

                    endforeach;

                endif;


                /**
                 * Operation validation
                 */
                if( !empty( $report['operations'] ) ):

                    foreach( $report['operations'] as $operation => $value ):

                        $totalOperations = count( $report['operations'][$operation] );

                        for( $i = 0; $i < $totalOperations; $i++ ):

                            if( $report['operations'][$operation]['operation'.($i+1)]['type'] !== $hideValidatorType ):

                                ?>
                                <div class="modelReport-item">
                                    <?php $type = $report['operations'][$operation]['operation'.($i+1)]['type']; ?>
                                    <div class="modelReport-item-img">
                                        <img src="./images/icons/<?= ( $type === "warning" || $type === "info" ? "warning_icon.png" : ( $type === "severe" || $type === "error" ? "red_cross_icon.png" : "checkgreen_icon.png") ); ?>">
                                        <div class="modelReport-item-type"> - <?= $report['operations'][$operation]['operation'.($i+1)]['type']; ?></div>
                                    </div>
                                    <div class="modelReport-item-name"><?= $report['operations'][$operation]['operation'.($i+1)]['name']; ?></div>
                                    <div class="modelReport-item-value"><?= $report['operations'][$operation]['operation'.($i+1)]['value']; ?></div>
                                    <div class="modelReport-item-message"><?= $report['operations'][$operation]['operation'.($i+1)]['message']; ?></div>

                                    <?php if( $report['operations'][$operation]['operation'.($i+1)]['valid'] === false ): ?>
                                    <div class="modelReport-item-info">
                                        <img src="./images/icons/arrow_right_up.png"><span><?= $report['operations'][$operation]['operation'.($i+1)]['info']; ?></span>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                <?php

                            endif;

                        endfor;

                    endforeach;

                endif;

            ?>

        </div>

    <?php endif; ?>

</div>

